### PR TITLE
Avatar component

### PR DESCRIPTION
**Pull request by ejthan**

### CODE REVIEW

**Comment by ejthan** [comment]
The border is not really showing in storybook, needs further investigation -> probably the border and background are the same color 😄

**Comment by djurango** [comment]
image

There is a very soft border/shadow around the avatar images in the "user suggestions" section.

Maybe we should add an option for borders/shadows to the avatar component?

**Comment by ejthan** [comment]
This option is already built in "showBorder"

**Comment by djurango** [comment]
> This option is already built in "showBorder"

> The border is not really showing in storybook, needs further investigation -> probably the border and background are the same color 😄


showBorder was not working since it was set with "border-6". 

The available ones by tailwind are the following:
image


We'll need a custom border-with here.

**Pull request merged**
